<?php
/**
 * Pluggable themes for Yii2
 *
 * @link      https://github.com/hiqdev/yii2-thememanager
 * @package   yii2-thememanager
 * @license   BSD-3-Clause
 * @copyright Copyright (c) 2015-2017, HiQDev (http://hiqdev.com/)
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'I already have a membership' => 'Я уже зарегистрирован',
    'I forgot my password' => 'Я забыл пароль',
    'Powered by' => 'Powered by',
    'Register a new membership' => 'Зарегистрироваться',
    'Theme Settings' => 'Настройки темы',
    'version' => 'версия',
    'Layout settings saved' => 'Настройки верстки сохранены',
    'Theme changed' => 'Тема изменена',
];
